In [1]:
from MLOps import DataGoverner
from MLOps import DBManager

dbm=DBManager(dev_db=True)

In [2]:
df = DataGoverner.load_tabular_dataset(dbm, 'Iris')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df = DataGoverner.load_tabular_dataset(dbm, 'Cereals')

In [5]:
df

,Cereal Name,Manufacturer,Type,Calories,Protein (g),Fat,Sodium,Dietary Fiber,Carbs,Sugars,Display Shelf,Potassium,Vitamins and Minerals,Serving Size Weight,Cups per Serving
0,100%_Bran,Nabisco,C,70.0,4.0,1.0,130.0,10.0,5.0,6.0,3.0,280.0,25.0,1.0,0.33
1,100%_Natural_Bran,Quaker Oats,C,120.0,3.0,5.0,15.0,2.0,8.0,8.0,3.0,135.0,0.0,1.0,-1.00
2,All-Bran,Kelloggs,C,70.0,4.0,1.0,260.0,9.0,7.0,5.0,3.0,320.0,25.0,1.0,0.33
3,All-Bran_with_Extra_Fiber,Kelloggs,C,50.0,4.0,0.0,140.0,14.0,8.0,0.0,3.0,330.0,25.0,1.0,0.50
4,Almond_Delight,Ralston Purina,C,110.0,2.0,2.0,200.0,1.0,14.0,8.0,3.0,-1.0,25.0,1.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Triples,General Mills,C,110.0,2.0,1.0,250.0,0.0,21.0,3.0,3.0,60.0,25.0,1.0,0.75
70,Trix,General Mills,C,110.0,1.0,1.0,140.0,0.0,13.0,12.0,2.0,25.0,25.0,1.0,1.00
71,Wheat_Chex,Ralston Purina,C,100.0,3.0,1.0,230.0,3.0,17.0,3.0,1.0,115.0,25.0,1.0,0.67
72,Wheaties,General Mills,C,100.0,3.0,1.0,200.0,3.0,17.0,3.0,1.0,110.0,25.0,1.0,1.00
73,Wheaties_Honey_Gold,General Mills,C,110.0,2.0,1.0,200.0,1.0,16.0,8.0,1.0,60.0,25.0,1.0,0.75